name: pytest

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
    - name: Test
      env:
        NAS_CREDS: ${{ secrets.NAS_CREDS }}
      run: |
        poetry run python -m coverage run --branch -m pytest tests/
    - name: Generate Report
      run: |
        poetry run python -m coverage html
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          htmlcov/*