name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
        ref: master


    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      id: release
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        root_options: "-vv"

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [release]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Not supporting macos due to https://github.com/stbrumme/hash-library/pull/4/files not being resolved

    steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
            ref: master
      
        # Used to host cibuildwheel
        - uses: actions/setup-python@v3
          with:
            python-version: '3.9'

        - name: Upgrade pip
          run: python -m pip install --upgrade pip
    
        - name: Install cibuildwheel
          run: python -m pip install cibuildwheel

        - name: Build wheels
          run: python -m cibuildwheel --output-dir dist
            # to supply options, put them in 'env', like:
            # env:
            #   CIBW_SOME_OPTION: value
          env:
            CIBW_BUILD: "cp39-*64 cp310-*64 cp311-*64 cp312-*64"
            CIBW_BEFORE_BUILD: git submodule update --init --recursive && pip install .
    
        - uses: actions/upload-artifact@v3
          with:
            path: ./dist/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: [build_wheels]
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
        ref: master

    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - name: Check dist
      run: ls -R dist

    - name: Publish package distributions to GitHub Releases
      id: github-release
      uses: python-semantic-release/upload-to-gh-release@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
